const assert=require('node:assert/strict');
const {createHpBridge}=require('./hp-bridge.cjs');
const http=require('node:http');
const os=require('node:os');
const {createObserverHost}=require('./ocr-observer.cjs');
const token='a'.repeat(48),groupCode='VPN-TEST';
(async()=>{
  const address=Object.values(os.networkInterfaces()).flat().find(n=>n.family==='IPv4'&&!n.internal)?.address;
  assert.ok(address,'A network interface is required for VPN transport test');
  const bridge=createHpBridge({token,groupCode,receiver:`http://${address}:5211`});
  await new Promise(resolve=>bridge.listen(0,'127.0.0.1',resolve));
  const vpn=http.createServer(bridge.listeners('request')[0]);
  await new Promise(resolve=>vpn.listen(0,address,resolve));
  const local=`http://127.0.0.1:${bridge.address().port}`,remote=`http://${address}:${vpn.address().port}`;
  const auth={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  let observer;
  try{
    const state={groupCode,roundNumber:1,roundPhase:'combat',map:'Test',isRunning:true,players:[{name:'Player',fullName:'Player#TEST',isAlive:true}]};
    const publish=await fetch(local+'/hp/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});
    const lifecycle=await publish.json();
    assert.equal((await fetch(remote+'/hp/state?groupCode='+groupCode)).status,401);
    assert.equal((await fetch(remote+'/hp/state?groupCode='+groupCode,{headers:{Authorization:'Bearer wrong'}})).status,401);
    assert.equal((await fetch(remote+'/hp/state?groupCode=OTHER',{headers:auth})).status,403);
    assert.equal((await fetch(remote+'/hp/all',{headers:auth})).status,403);
    assert.equal((await fetch(remote+'/hp/pairing',{headers:auth})).status,403);
    const pairing=await(await fetch(local+'/hp/pairing')).json();
    assert.equal(pairing.key,token);assert.equal(pairing.groupCode,groupCode);
    assert.equal((await fetch(local+'/hp/pairing',{headers:{Origin:'https://example.com'}})).status,403);
    assert.equal((await fetch(remote+'/hp/state',{method:'POST',headers:auth,body:JSON.stringify(state)})).status,403);
    assert.equal((await fetch(remote+'/hp/state?groupCode='+groupCode,{headers:auth})).status,200);
    const reading={groupCode,playerName:'Player',hp:35,epoch:lifecycle.players[0].epoch};
    const post=data=>fetch(remote+'/hp',{method:'POST',headers:auth,body:JSON.stringify(data)});
    assert.equal((await post({...reading,groupCode:'OTHER'})).status,403);
    assert.equal((await post({...reading,epoch:'old'})).status,409);
    assert.equal((await post(reading)).status,200);
    assert.equal((await(await fetch(local+'/hp/all')).json())[0].hp,35);
    observer=createObserverHost();
    await new Promise(resolve=>observer.listen(0,'127.0.0.1',resolve));
    const browser=`http://127.0.0.1:${observer.address().port}`;
    assert.equal((await fetch(browser+'/hp-reader/dual.html')).status,200);
    assert.equal((await fetch(browser+'/observer/hp/state')).status,502);
    const pair=await fetch(browser+'/observer/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receiver:remote,token,groupCode})});
    assert.equal(pair.status,200);
    const observed=await(await fetch(browser+'/observer/hp/state')).json();
    assert.equal(observed.players[0].epoch,lifecycle.players[0].epoch);
    assert.equal((await fetch(browser+'/observer/hp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...reading,hp:42})})).status,200);
    assert.equal((await(await fetch(local+'/hp/all')).json())[0].hp,42);
    assert.equal((await fetch(browser+'/observer/connect',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:'{}'})).status,403);
    console.log('PASS: authenticated network delivery, wrong key/group denied, remote lifecycle writes denied, stale epochs denied');
    console.log('PASS: standalone observer UI, pairing, lifecycle relay, HP relay and foreign origin rejection');
  }finally{observer?.close();await Promise.all([new Promise(resolve=>vpn.close(resolve)),new Promise(resolve=>bridge.close(resolve))]);}
})().catch(error=>{console.error(error);process.exitCode=1;});
